version: 2
jobs:
  package:
    working_directory: ~/RTKPythonPackage-build
    machine: true
    steps:
      - checkout:
          path: ~/RTKPythonPackage
      - run:
          name: Configure
          no_output_timeout: 1.0h
          command: |
            cmake ~/RTKPythonPackage
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            chmod u+x BuildLinuxWheels.sh
            ./BuildLinuxWheels.sh
      - store_artifacts:
          path: dist
          destination: dist

workflows:
    version: 2
    build-test:
      jobs:
        - package
